name: build
on: [push, pull_request]
jobs:
  xenial:
    container: 
      image: swift:xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: apt-get -qq update && apt-get -q -y install libpq-dev libssl-dev zlib1g-dev
    - run: swift test --enable-test-discovery --sanitize=thread
  bionic:
    container: 
      image: swift:bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: apt-get -qq update && apt-get -q -y install libpq-dev libssl-dev zlib1g-dev
    - run: swift test --enable-test-discovery --sanitize=thread
  bionic-release:
    container: 
      image: swift:bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: apt-get -qq update && apt-get -q -y install libpq-dev libssl-dev zlib1g-dev
    - run: swift build -c release
